import Foundation

/// The output of `ReinstallScriptGenerator.generate(missing:)`.
///
/// Return type decision: this is a new type rather than reusing `GeneratedScript` because
/// `GeneratedScript`'s `skippedReadOnly` and `warnedDenylisted` fields are uninstall-specific
/// and have no meaning in a reinstall context.
public struct GeneratedReinstallScript: Sendable {
    /// Complete shell script text, ready to paste into Terminal.
    public let scriptText: String

    public init(scriptText: String) {
        self.scriptText = scriptText
    }
}

/// Generates a shell script that reinstalls packages that were recorded in a snapshot
/// but are no longer present in the live inventory.
///
/// This is a pure value: it reads `[MissingPackage]` and produces a script string.
/// It never touches the filesystem, spawns a process, or accesses the database.
///
/// No snapshot is captured before calling this method — reinstalling is additive,
/// not destructive, so the snapshot-before-action rule does not apply.
///
/// No denylist filtering is applied — the denylist governs removal; reinstalling
/// a common essential is harmless.
///
/// Version fidelity per manager:
/// - pip / npm / pipx / gem: pins the exact recorded version.
/// - uv: emits manual-review guidance because snapshots do not retain full receipts.
/// - cargo: preserves the recorded registry, git revision, or local path; registry
///   installs also pin the recorded version.
/// - brew / brewCask: cannot pin; installs the current version. An inline comment
///   names the recorded version so the user can assess the difference.
/// - mas: no CLI reinstall path; emits a comment directing the user to the App Store.
public struct ReinstallScriptGenerator: Sendable {
    public init() {}

    public func generate(missing: [MissingPackage]) -> GeneratedReinstallScript {
        var out: [String] = []
        appendHeader(to: &out)
        appendManagerSections(missing: missing, to: &out)
        return GeneratedReinstallScript(scriptText: out.joined(separator: "\n") + "\n")
    }

    // MARK: - Header

    private func appendHeader(to out: inout [String]) {
        let fmt = makeISO8601Formatter()
        out.append("#!/usr/bin/env bash")
        out.append("# Generated by Installory on \(fmt.string(from: Date()))")
        out.append("# Review every line before running. You can run this script manually")
        out.append("# in Terminal — Installory does not execute it for you.")
        out.append("set -euo pipefail")
    }

    // MARK: - Manager sections

    private static let managerOrder: [PackageManager] = [
        .brew, .brewCask, .pip, .npm, .pipx, .uv, .cargo, .gem, .mas,
    ]

    private func appendManagerSections(missing: [MissingPackage], to out: inout [String]) {
        let handledSet = Set(Self.managerOrder)

        for manager in Self.managerOrder {
            let pkgs = missing.filter { $0.manager == manager }
            guard !pkgs.isEmpty else { continue }
            appendSection(manager: manager, packages: pkgs, to: &out)
        }

        let extra = Set(missing.map { $0.manager })
            .subtracting(handledSet)
            .sorted { $0.rawValue < $1.rawValue }
        for manager in extra {
            let pkgs = missing.filter { $0.manager == manager }
            appendSection(manager: manager, packages: pkgs, to: &out)
        }
    }

    private func appendSection(manager: PackageManager, packages: [MissingPackage], to out: inout [String]) {
        if manager.groupsByQualifier {
            let byQualifier = Dictionary(grouping: packages) { $0.package.qualifier ?? "" }
            for qualifier in byQualifier.keys.sorted() {
                let pkgs = byQualifier[qualifier]!
                out.append("")
                out.append(qualifiedSectionHeader(for: manager, qualifier: qualifier))
                for mp in pkgs { appendInstallLine(for: mp, to: &out) }
            }
        } else {
            out.append("")
            out.append(sectionHeader(for: manager))
            let orderedPackages = manager == .pipx || manager == .uv
                ? packages.sorted(by: pipxPackageOrder)
                : packages
            for mp in orderedPackages { appendInstallLine(for: mp, to: &out) }
        }
    }

    private func qualifiedSectionHeader(for manager: PackageManager, qualifier: String) -> String {
        guard !qualifier.isEmpty else { return sectionHeader(for: manager) }
        let commentQualifier = shellCommentText(qualifier)
        switch manager {
        case .pip: return "# === pip (interpreter: \(commentQualifier)) ==="
        case .npm: return "# === npm (global: \(commentQualifier)) ==="
        case .gem: return "# === Ruby Gems (\(commentQualifier)) ==="
        default:   return sectionHeader(for: manager)
        }
    }

    private func appendInstallLine(for mp: MissingPackage, to out: inout [String]) {
        switch mp.manager {
        case .mas:
            out.append("# \(shellCommentText(mp.package.name)): reinstall from the Mac App Store (no CLI reinstall path)")

        case .brew:
            let cmd = "brew install \(shellArgument(mp.package.name))"
            out.append("# snapshot recorded \(shellCommentText(mp.package.version)); Homebrew installs the current version")
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .brewCask:
            let cmd = "brew install --cask \(shellArgument(mp.package.name))"
            out.append("# snapshot recorded \(shellCommentText(mp.package.version)); Homebrew installs the current version")
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .pip:
            let interpreter = mp.package.qualifier ?? "python3"
            let spec = "\(mp.package.name)==\(mp.package.version)"
            let cmd = "\(shellArgument(interpreter)) -m pip install \(shellArgument(spec))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .npm:
            let spec = "\(mp.package.name)@\(mp.package.version)"
            let npm = ManagerBinaryResolver.npm(forQualifier: mp.package.qualifier)
            let cmd = "\(shellArgument(npm)) install -g \(shellArgument(spec))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .pipx:
            let spec = "\(mp.package.name)==\(mp.package.version)"
            let target = PipxEnvironmentIdentity.reinstallTarget(
                distributionName: mp.package.name,
                qualifier: mp.package.qualifier
            )
            switch target {
            case .base:
                appendCommand("pipx install \(shellArgument(spec))", to: &out)
            case .suffixed(let suffix):
                let suffixOption = shellArgument("--suffix=\(suffix)")
                appendCommand(
                    "pipx install \(shellArgument(spec)) \(suffixOption)",
                    to: &out
                )
            case .manualReview:
                let recordedEnvironment = mp.package.qualifier
                    .map(shellCommentText) ?? "no recorded environment path"
                out.append(
                    "# Manual review required: cannot safely derive pipx --suffix for "
                        + "\(shellCommentText(spec)) from \(recordedEnvironment); "
                        + "no install command generated."
                )
            }

        case .uv:
            let recordedEnvironment = mp.package.qualifier
                .map(shellCommentText) ?? "no recorded environment path"
            out.append(
                "# Manual review required: uv tool \(shellCommentText(mp.package.name)) "
                    + "\(shellCommentText(mp.package.version)) was recorded at "
                    + "\(recordedEnvironment), but its full install receipt is not in the snapshot; "
                    + "no install command generated."
            )

        case .cargo:
            guard let source = CargoRestoreSource(recordedSource: mp.package.qualifier) else {
                let recordedSource = mp.package.qualifier
                    .map(shellCommentText) ?? "no recorded source"
                out.append(
                    "# Manual review required: cannot faithfully restore Cargo package "
                        + "\(shellCommentText(mp.package.name)) \(shellCommentText(mp.package.version)) "
                        + "from \(recordedSource); no install command generated."
                )
                return
            }
            appendCommand(
                source.installCommand(
                    packageName: mp.package.name,
                    version: mp.package.version
                ),
                to: &out
            )

        case .gem:
            let gem = ManagerBinaryResolver.gem(forQualifier: mp.package.qualifier)
            var cmd = "\(shellArgument(gem.binary)) install \(shellArgument(mp.package.name))"
                + " -v \(shellArgument(mp.package.version))"
            if let installDir = gem.installDir {
                cmd += " --install-dir \(shellArgument(installDir))"
            }
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)
        }
    }

    private func sectionHeader(for manager: PackageManager) -> String {
        switch manager {
        case .brew:     return "# === Homebrew Formulae ==="
        case .brewCask: return "# === Homebrew Casks ==="
        case .pip:      return "# === pip ==="
        case .npm:      return "# === npm (global) ==="
        case .pipx:     return "# === pipx ==="
        case .uv:       return "# === uv tools ==="
        case .cargo:    return "# === Cargo (Rust) ==="
        case .gem:      return "# === Ruby Gems ==="
        case .mas:      return "# === Mac App Store ==="
        }
    }

    private func appendCommand(_ command: String, to out: inout [String]) {
        out.append(shellEchoLine(for: command))
        out.append(command)
    }

    private func pipxPackageOrder(_ lhs: MissingPackage, _ rhs: MissingPackage) -> Bool {
        let lhsQualifier = lhs.package.qualifier ?? ""
        let rhsQualifier = rhs.package.qualifier ?? ""
        if lhsQualifier != rhsQualifier { return lhsQualifier < rhsQualifier }
        if lhs.package.name != rhs.package.name {
            return lhs.package.name < rhs.package.name
        }
        return lhs.package.version < rhs.package.version
    }

    private func makeISO8601Formatter() -> ISO8601DateFormatter {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }
}

private enum CargoRestoreSource {
    enum GitSelector {
        case branch(String)
        case tag(String)
        case revision(String)
    }

    case cratesIO
    case registry(index: String)
    case git(url: String, selector: GitSelector?)
    case path(String)

    init?(recordedSource: String?) {
        guard let recordedSource, Self.isSafe(recordedSource) else { return nil }

        if recordedSource.hasPrefix("registry+") {
            let index = String(recordedSource.dropFirst("registry+".count))
            guard Self.isValidURL(index) else { return nil }
            self = Self.isCratesIOIndex(index) ? .cratesIO : .registry(index: index)
            return
        }

        if recordedSource.hasPrefix("git+") {
            let sourceURL = String(recordedSource.dropFirst("git+".count))
            guard var components = URLComponents(string: sourceURL),
                  let scheme = components.scheme, !scheme.isEmpty else {
                return nil
            }

            let queryItems = components.queryItems ?? []
            guard queryItems.count <= 1 else { return nil }
            let querySelector: GitSelector?
            if let item = queryItems.first {
                guard let value = item.value, Self.isSafe(value) else { return nil }
                switch item.name {
                case "branch": querySelector = .branch(value)
                case "tag": querySelector = .tag(value)
                case "rev": querySelector = .revision(value)
                default: return nil
                }
            } else {
                querySelector = nil
            }

            let preciseRevision = components.fragment
            if let preciseRevision, !Self.isSafe(preciseRevision) { return nil }
            components.query = nil
            components.fragment = nil
            guard let gitURL = components.string, Self.isValidURL(gitURL) else { return nil }

            self = .git(
                url: gitURL,
                selector: preciseRevision.map(GitSelector.revision) ?? querySelector
            )
            return
        }

        if recordedSource.hasPrefix("path+") {
            let sourceURL = String(recordedSource.dropFirst("path+".count))
            guard var components = URLComponents(string: sourceURL),
                  components.scheme == "file",
                  components.query == nil else {
                return nil
            }
            components.fragment = nil
            guard let fileURLString = components.string,
                  let fileURL = URL(string: fileURLString),
                  fileURL.isFileURL,
                  fileURL.host == nil || fileURL.host == "",
                  fileURL.path.hasPrefix("/"),
                  Self.isSafe(fileURL.path) else {
                return nil
            }
            self = .path(fileURL.path)
            return
        }

        return nil
    }

    func installCommand(packageName: String, version: String) -> String {
        switch self {
        case .cratesIO:
            return "cargo install \(shellArgument(packageName)) --version \(shellArgument(version))"

        case .registry(let index):
            return "cargo install \(shellArgument(packageName)) --version \(shellArgument(version))"
                + " --index \(shellArgument(index))"

        case .git(let url, let selector):
            var command = "cargo install --git \(shellArgument(url))"
            if let selector {
                switch selector {
                case .branch(let branch):
                    command += " --branch \(shellArgument(branch))"
                case .tag(let tag):
                    command += " --tag \(shellArgument(tag))"
                case .revision(let revision):
                    command += " --rev \(shellArgument(revision))"
                }
            }
            return command + " \(shellArgument(packageName))"

        case .path(let path):
            return "cargo install --path \(shellArgument(path))"
        }
    }

    private static func isCratesIOIndex(_ index: String) -> Bool {
        let normalized = index.hasSuffix("/") ? String(index.dropLast()) : index
        return normalized == "https://github.com/rust-lang/crates.io-index"
            || normalized == "https://index.crates.io"
            || normalized == "sparse+https://index.crates.io"
    }

    private static func isValidURL(_ value: String) -> Bool {
        guard isSafe(value) else { return false }
        let transportURL = value.hasPrefix("sparse+")
            ? String(value.dropFirst("sparse+".count))
            : value
        guard let components = URLComponents(string: transportURL),
              let scheme = components.scheme, !scheme.isEmpty else {
            return false
        }
        return components.host != nil || scheme == "file"
    }

    private static func isSafe(_ value: String) -> Bool {
        guard !value.isEmpty else { return false }
        let unsafeScalars = CharacterSet.controlCharacters.union(.newlines)
        return value.unicodeScalars.allSatisfy { !unsafeScalars.contains($0) }
    }
}
