import Foundation

/// The output of `ReinstallScriptGenerator.generate(missing:)`.
///
/// Return type decision: this is a new type rather than reusing `GeneratedScript` because
/// `GeneratedScript`'s `skippedReadOnly` and `warnedDenylisted` fields are uninstall-specific
/// and have no meaning in a reinstall context.
public struct GeneratedReinstallScript: Sendable {
    /// Complete shell script text, ready to paste into Terminal.
    public let scriptText: String

    public init(scriptText: String) {
        self.scriptText = scriptText
    }
}

/// Generates a shell script that reinstalls packages that were recorded in a snapshot
/// but are no longer present in the live inventory.
///
/// This is a pure value: it reads `[MissingPackage]` and produces a script string.
/// It never touches the filesystem, spawns a process, or accesses the database.
///
/// No snapshot is captured before calling this method — reinstalling is additive,
/// not destructive, so the snapshot-before-action rule does not apply.
///
/// No denylist filtering is applied — the denylist governs removal; reinstalling
/// a common essential is harmless.
///
/// Version fidelity per manager:
/// - pip / npm / pipx / cargo / gem: pins the exact recorded version.
/// - brew / brewCask: cannot pin; installs the current version. An inline comment
///   names the recorded version so the user can assess the difference.
/// - mas: no CLI reinstall path; emits a comment directing the user to the App Store.
public struct ReinstallScriptGenerator: Sendable {
    public init() {}

    public func generate(missing: [MissingPackage]) -> GeneratedReinstallScript {
        var out: [String] = []
        appendHeader(to: &out)
        appendManagerSections(missing: missing, to: &out)
        return GeneratedReinstallScript(scriptText: out.joined(separator: "\n") + "\n")
    }

    // MARK: - Header

    private func appendHeader(to out: inout [String]) {
        let fmt = makeISO8601Formatter()
        out.append("#!/usr/bin/env bash")
        out.append("# Generated by Installory on \(fmt.string(from: Date()))")
        out.append("# Review every line before running. You can run this script manually")
        out.append("# in Terminal — Installory does not execute it for you.")
        out.append("set -euo pipefail")
    }

    // MARK: - Manager sections

    private static let managerOrder: [PackageManager] = [
        .brew, .brewCask, .pip, .npm, .pipx, .cargo, .gem, .mas,
    ]

    private func appendManagerSections(missing: [MissingPackage], to out: inout [String]) {
        let handledSet = Set(Self.managerOrder)

        for manager in Self.managerOrder {
            let pkgs = missing.filter { $0.manager == manager }
            guard !pkgs.isEmpty else { continue }
            appendSection(manager: manager, packages: pkgs, to: &out)
        }

        let extra = Set(missing.map { $0.manager })
            .subtracting(handledSet)
            .sorted { $0.rawValue < $1.rawValue }
        for manager in extra {
            let pkgs = missing.filter { $0.manager == manager }
            appendSection(manager: manager, packages: pkgs, to: &out)
        }
    }

    private func appendSection(manager: PackageManager, packages: [MissingPackage], to out: inout [String]) {
        if manager == .pip {
            let byInterpreter = Dictionary(grouping: packages) { $0.package.qualifier ?? "" }
            for interpreter in byInterpreter.keys.sorted() {
                let pkgs = byInterpreter[interpreter]!
                out.append("")
                out.append(interpreter.isEmpty
                    ? "# === pip ==="
                    : "# === pip (interpreter: \(interpreter)) ===")
                for mp in pkgs { appendInstallLine(for: mp, to: &out) }
            }
        } else {
            out.append("")
            out.append(sectionHeader(for: manager))
            for mp in packages { appendInstallLine(for: mp, to: &out) }
        }
    }

    private func appendInstallLine(for mp: MissingPackage, to out: inout [String]) {
        switch mp.manager {
        case .mas:
            out.append("# \(mp.package.name): reinstall from the Mac App Store (no CLI reinstall path)")

        case .brew:
            let cmd = "brew install \(shellArgument(mp.package.name))"
            out.append("# snapshot recorded \(mp.package.version); Homebrew installs the current version")
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .brewCask:
            let cmd = "brew install --cask \(shellArgument(mp.package.name))"
            out.append("# snapshot recorded \(mp.package.version); Homebrew installs the current version")
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .pip:
            let interpreter = mp.package.qualifier ?? "python3"
            let spec = "\(mp.package.name)==\(mp.package.version)"
            let cmd = "\(shellArgument(interpreter)) -m pip install \(shellArgument(spec))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .npm:
            let spec = "\(mp.package.name)@\(mp.package.version)"
            let cmd = "npm install -g \(shellArgument(spec))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .pipx:
            let spec = "\(mp.package.name)==\(mp.package.version)"
            let cmd = "pipx install \(shellArgument(spec))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .cargo:
            let cmd = "cargo install \(shellArgument(mp.package.name)) --version \(shellArgument(mp.package.version))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)

        case .gem:
            let cmd = "gem install \(shellArgument(mp.package.name)) -v \(shellArgument(mp.package.version))"
            out.append(shellEchoLine(for: cmd))
            out.append(cmd)
        }
    }

    private func sectionHeader(for manager: PackageManager) -> String {
        switch manager {
        case .brew:     return "# === Homebrew Formulae ==="
        case .brewCask: return "# === Homebrew Casks ==="
        case .pip:      return "# === pip ==="
        case .npm:      return "# === npm (global) ==="
        case .pipx:     return "# === pipx ==="
        case .cargo:    return "# === Cargo (Rust) ==="
        case .gem:      return "# === Ruby Gems ==="
        case .mas:      return "# === Mac App Store ==="
        }
    }

    private func makeISO8601Formatter() -> ISO8601DateFormatter {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }
}
